# Generated by Django 5.2.4 on 2025-07-04 12:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254)),
                ('full_address', models.TextField(max_length=250)),
                ('landmark', models.CharField(max_length=150)),
                ('google_map_link', models.URLField(blank=True, null=True)),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('gate_closing_time', models.TimeField(blank=True, null=True)),
                ('minimum_stay', models.PositiveIntegerField(help_text='In months')),
                ('available_from', models.DateField()),
                ('pg_type', models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('COED', 'co-ed')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='pg_model',
        ),
    ]
