# Generated by Django 5.2.4 on 2025-07-04 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_finder', '0002_pg_delete_pg_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pg_photos/')),
                ('description', models.CharField(blank=True, max_length=150)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_finder.pg')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rooms_available', models.PositiveIntegerField()),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pg_finder.pg')),
            ],
        ),
    ]
