# Generated by Django 5.2.4 on 2025-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_finder', '0003_media_roomdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pg',
            name='image',
            field=models.ImageField(blank=True, upload_to='pg_photos/'),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
