# Generated by Django 5.2.4 on 2025-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_finder', '0004_pg_description_pg_image_delete_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='image',
            field=models.ImageField(upload_to='pg_photos/'),
        ),
    ]
