# Generated by Django 5.2.4 on 2025-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_finder', '0005_alter_pg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='pg_ac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pg',
            name='pg_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pg',
            name='pg_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pg',
            name='pg_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
