# Generated by Django 5.2.4 on 2025-07-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_finder', '0008_pg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='city',
            field=models.CharField(default='karnataka', null=True),
        ),
    ]
