# Generated by Django 5.2.4 on 2025-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_finder', '0009_pg_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='full_address',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
